# common parts
. $HOME/.dotfiles/common/profile
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

ulimit -n 10000

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/oscar.renalias/.sdkman"
[[ -s "/Users/oscar.renalias/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/oscar.renalias/.sdkman/bin/sdkman-init.sh"
# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/oscar.renalias/google-cloud-sdk/path.bash.inc' ]; then source '/Users/oscar.renalias/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/oscar.renalias/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/oscar.renalias/google-cloud-sdk/completion.bash.inc'; fi
